In [ ]:
# data fromam: combine the multiple series called df

In [2]:

import numpy as np
import pandas as pd

In [5]:
data = {
    "Name": ["Naveen", "Rahul", "Priya", "Anjali", "Kiran"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 78, 92, 74, 88],
    "Branch": ["CSE", "ECE", "CSE", "ME", "CSE"]
}
df = pd.DataFrame(data)

In [9]:
df['Name']

0    Naveen
1     Rahul
2     Priya
3    Anjali
4     Kiran
Name: Name, dtype: object

In [10]:
df[['Name', 'Age']]

     Name  Age
0  Naveen   20
1   Rahul   21
2   Priya   19
3  Anjali   22
4   Kiran   20

In [12]:
df['city']=['m','b', 'h','d','r']

In [13]:
df['city']

0    m
1    b
2    h
3    d
4    r
Name: city, dtype: object

In [14]:
df

     Name  Age  Marks Branch city
0  Naveen   20     85    CSE    m
1   Rahul   21     78    ECE    b
2   Priya   19     92    CSE    h
3  Anjali   22     74     ME    d
4   Kiran   20     88    CSE    r

In [16]:
df.drop('city' , axis=1) # same but not achualy not dlete the data is df as in collumn

     Name  Age  Marks Branch
0  Naveen   20     85    CSE
1   Rahul   21     78    ECE
2   Priya   19     92    CSE
3  Anjali   22     74     ME
4   Kiran   20     88    CSE

In [17]:
df

     Name  Age  Marks Branch city
0  Naveen   20     85    CSE    m
1   Rahul   21     78    ECE    b
2   Priya   19     92    CSE    h
3  Anjali   22     74     ME    d
4   Kiran   20     88    CSE    r

In [18]:
df.drop('city',axis=1, inplace=True)# drop colleum with real data

In [19]:
df

     Name  Age  Marks Branch
0  Naveen   20     85    CSE
1   Rahul   21     78    ECE
2   Priya   19     92    CSE
3  Anjali   22     74     ME
4   Kiran   20     88    CSE

In [20]:
# drop row
df.drop(0, axis=0)  # o is row and 1 is columen

     Name  Age  Marks Branch
1   Rahul   21     78    ECE
2   Priya   19     92    CSE
3  Anjali   22     74     ME
4   Kiran   20     88    CSE

In [21]:
df

     Name  Age  Marks Branch
0  Naveen   20     85    CSE
1   Rahul   21     78    ECE
2   Priya   19     92    CSE
3  Anjali   22     74     ME
4   Kiran   20     88    CSE

In [22]:
# accesing rwo using loc
df.loc[0] #loc is location

Name      Naveen
Age           20
Marks         85
Branch       CSE
Name: 0, dtype: object

In [24]:
df.loc[[1,0]]

     Name  Age  Marks Branch
1   Rahul   21     78    ECE
0  Naveen   20     85    CSE

In [27]:
# selecting the subset of row and columns
df.loc[[0,1]][["Branch","Marks"]]

  Branch  Marks
0    CSE     85
1    ECE     78

In [29]:
df.loc[[3,4]][["Name","Age"]]

     Name  Age
3  Anjali   22
4   Kiran   20

In [ ]:
# condition selection 
<,>

In [32]:
df[df["Age"]>20]

     Name  Age  Marks Branch
1   Rahul   21     78    ECE
3  Anjali   22     74     ME

In [33]:
df

     Name  Age  Marks Branch
0  Naveen   20     85    CSE
1   Rahul   21     78    ECE
2   Priya   19     92    CSE
3  Anjali   22     74     ME
4   Kiran   20     88    CSE

In [40]:
df[(df["Age"] > 20) & (df["Marks"] > 80)]

Empty DataFrame
Columns: [Name, Age, Marks, Branch]
Index: []