In [ ]:
#marging and concatintation

In [ ]:
# marging 2 dataframes

In [3]:
import numpy as np
import pandas as pd

In [5]:
students = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4, 5],
    "Name": ["Naveen", "Rahul", "Priya", "Anjali", "Kiran"],
    "Age": [20, 21, 19, 22, 20]
})

marks = pd.DataFrame({
    "Student_ID": [1, 2, 3, 6],
    "Marks": [85, 78, 92, 88],
    "Grade": ["A", "B", "A", "B"]
})
students

   Student_ID    Name  Age
0           1  Naveen   20
1           2   Rahul   21
2           3   Priya   19
3           4  Anjali   22
4           5   Kiran   20

In [6]:
pd.merge(students,marks)

   Student_ID    Name  Age  Marks Grade
0           1  Naveen   20     85     A
1           2   Rahul   21     78     B
2           3   Priya   19     92     A

In [11]:
pd.merge(students ,marks, on="Student_ID" ,how ="outer")   #mearg all

   Student_ID    Name   Age  Marks Grade
0           1  Naveen  20.0   85.0     A
1           2   Rahul  21.0   78.0     B
2           3   Priya  19.0   92.0     A
3           4  Anjali  22.0    NaN   NaN
4           5   Kiran  20.0    NaN   NaN
5           6     NaN   NaN   88.0     B

In [12]:
pd.merge(students ,marks, on="Student_ID" ,how ="left")   #lefte = student

   Student_ID    Name  Age  Marks Grade
0           1  Naveen   20   85.0     A
1           2   Rahul   21   78.0     B
2           3   Priya   19   92.0     A
3           4  Anjali   22    NaN   NaN
4           5   Kiran   20    NaN   NaN

In [13]:
pd.merge(students ,marks, on="Student_ID" ,how ="right")  #right = marks

   Student_ID    Name   Age  Marks Grade
0           1  Naveen  20.0     85     A
1           2   Rahul  21.0     78     B
2           3   Priya  19.0     92     A
3           6     NaN   NaN     88     B

In [ ]:
#concatination

In [17]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Naveen", "Rahul", "Priya"],
    "Marks": [85, 78, 92]
})
df2 = pd.DataFrame( {
    "ID": [4, 5, 6],
    "Name": ["Anjali", "Kiran", "Arun"],
    "Marks": [74, 88, 81]
})

In [18]:
df1

   ID    Name  Marks
0   1  Naveen     85
1   2   Rahul     78
2   3   Priya     92

In [19]:
pd.concat([df1,df2]) #based on columne

   ID    Name  Marks
0   1  Naveen     85
1   2   Rahul     78
2   3   Priya     92
0   4  Anjali     74
1   5   Kiran     88
2   6    Arun     81

In [20]:
pd.concat([df1,df2],axis=1)

   ID    Name  Marks  ID    Name  Marks
0   1  Naveen     85   4  Anjali     74
1   2   Rahul     78   5   Kiran     88
2   3   Priya     92   6    Arun     81

**joing 2 dataframes**

In [32]:
df1 = pd.DataFrame({
    "Name": ["Naveen", "Rahul", "Priya"],
    "Marks": [85, 78, 92]
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Grade": ["A", "B", "A"]
})

In [33]:
df1

     Name  Marks
1  Naveen     85
2   Rahul     78
3   Priya     92

In [34]:
df2

   ID Grade
0   1     A
1   2     B
2   4     A

In [38]:
df1.join(df2 )

     Name  Marks   ID Grade
1  Naveen     85  2.0     B
2   Rahul     78  4.0     A
3   Priya     92  NaN   NaN