In [ ]:
# mising data

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {

    "Name": ["Naveen", "Rahul", "Priya", "Anjali", "Kiran"],
    "Age": [20, None, 19, 22, None],
    "Marks": [85, 78, None, 74, 88],
    "Branch": ["CSE", "ECE", None, "ME", "CSE"]
}
df = pd.DataFrame(data)

In [4]:
df

     Name   Age  Marks Branch
0  Naveen  20.0   85.0    CSE
1   Rahul   NaN   78.0    ECE
2   Priya  19.0    NaN   None
3  Anjali  22.0   74.0     ME
4   Kiran   NaN   88.0    CSE

In [7]:
df.isna()   #to see in t or f value

    Name    Age  Marks  Branch
0  False  False  False   False
1  False   True  False   False
2  False  False   True    True
3  False  False  False   False
4  False   True  False   False

In [9]:
df.isna().sum()  #take sum of the in the present noul value or not

Name      0
Age       2
Marks     1
Branch    1
dtype: int64

In [ ]:
# removingthe mising data

In [10]:
df.dropna() #if  row contains all value it retunor else al table drope

     Name   Age  Marks Branch
0  Naveen  20.0   85.0    CSE
3  Anjali  22.0   74.0     ME

In [14]:
df.dropna(thresh=4)  #means 4 non nul valuse

     Name   Age  Marks Branch
0  Naveen  20.0   85.0    CSE
3  Anjali  22.0   74.0     ME

In [ ]:
# filing mising data

In [15]:
df.fillna(0)

     Name   Age  Marks Branch
0  Naveen  20.0   85.0    CSE
1   Rahul   0.0   78.0    ECE
2   Priya  19.0    0.0      0
3  Anjali  22.0   74.0     ME
4   Kiran   0.0   88.0    CSE

In [21]:
values={"Age":10, "Marks":50,"Branch":"mba"}
df.fillna(value=values)

     Name   Age  Marks Branch
0  Naveen  20.0   85.0    CSE
1   Rahul  10.0   78.0    ECE
2   Priya  19.0   50.0    mba
3  Anjali  22.0   74.0     ME
4   Kiran  10.0   88.0    CSE